name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: u2949-pmnjdp9drwa7
          server: ssh.upulsanjeewagamage.com
          port: 18765
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./wp-content/
          remote_path: /home/u2949-pmnjdp9drwa7/www/upulsanjeewagamage.com/public_html/wp-content/
