name: Deploy Theme to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SFTP Deploy
      uses: laryve/sftp-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        localDir: ./wp-content/themes/generatepress_child/
        remoteDir: /www/upulsanjeewagamage.com/public_html/wp-content/themes/generatepress_child/
