name: Deploy Theme to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SFTP Deploy
      uses: appleboy/sftp-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        source: "wp-content/themes/generatepress_child/*"
        target: "/www/upulsanjeewagamage.com/public_html/wp-content/themes/generatepress_child/"
