name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        run: |
          apt-get update && apt-get install -y lftp
          lftp -c "open -u $SFTP_USER,$SFTP_PASS sftp://ssh.upulsanjeewagamage.com:18765; mirror -R ./wp-content /home/u2949-pmnjdp9drwa7/www/staging.upulsanjeewagamage.com/public_html/wp-content"
        env:
          SFTP_USER: u2949-pmnjdp9drwa7
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
