name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: u2949-pmnjdp9drwa7
          server: ssh.upulsanjeewagamage.com
          port: 18765
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          ssh_private_key_passphrase: ${{ secrets.SFTP_PASSPHRASE }}
          local_path: ./wp-content/
          remote_path: /home/u2949-pmnjdp9drwa7/www/staging.upulsanjeewagamage.com/public_html/wp-content/
