name: Deploy Theme to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Simple Test Action
      uses: actions/hello-world-javascript-action@v2
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SFTP Deploy
      uses: appleboy/sftp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.FTP_PORT }}
        source: "wp-content/themes/generatepress_child/"
        target: "/www/upulsanjeewagamage.com/public_html/wp-content/themes/generatepress_child/"
