name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ssh.upulsanjeewagamage.com
          port: 18765
          username: u2949-pmnjdp9drwa7
          password: ${{ secrets.SFTP_PASS }}
          local-dir: ./wp-content/
          server-dir: /home/u2949-pmnjdp9drwa7/www/staging.upulsanjeewagamage.com/public_html/wp-content/
